#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GPS_TRAKER")]
	public partial class GpsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCat_Perfiles(Cat_Perfiles instance);
    partial void UpdateCat_Perfiles(Cat_Perfiles instance);
    partial void DeleteCat_Perfiles(Cat_Perfiles instance);
    partial void InsertCat_Status_Vehiculo(Cat_Status_Vehiculo instance);
    partial void UpdateCat_Status_Vehiculo(Cat_Status_Vehiculo instance);
    partial void DeleteCat_Status_Vehiculo(Cat_Status_Vehiculo instance);
    partial void InsertCat_Tipo_Vehiculo(Cat_Tipo_Vehiculo instance);
    partial void UpdateCat_Tipo_Vehiculo(Cat_Tipo_Vehiculo instance);
    partial void DeleteCat_Tipo_Vehiculo(Cat_Tipo_Vehiculo instance);
    partial void InsertCat_Unidad_Gps(Cat_Unidad_Gps instance);
    partial void UpdateCat_Unidad_Gps(Cat_Unidad_Gps instance);
    partial void DeleteCat_Unidad_Gps(Cat_Unidad_Gps instance);
    partial void InsertCtrl_Gps_Posicion(Ctrl_Gps_Posicion instance);
    partial void UpdateCtrl_Gps_Posicion(Ctrl_Gps_Posicion instance);
    partial void DeleteCtrl_Gps_Posicion(Ctrl_Gps_Posicion instance);
    partial void InsertCtrl_Usuarios(Ctrl_Usuarios instance);
    partial void UpdateCtrl_Usuarios(Ctrl_Usuarios instance);
    partial void DeleteCtrl_Usuarios(Ctrl_Usuarios instance);
    partial void InsertCtrl_Vehiculos(Ctrl_Vehiculos instance);
    partial void UpdateCtrl_Vehiculos(Ctrl_Vehiculos instance);
    partial void DeleteCtrl_Vehiculos(Ctrl_Vehiculos instance);
    #endregion
		
		public GpsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GPS_TRAKERConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GpsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GpsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GpsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GpsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cat_Perfiles> Cat_Perfiles
		{
			get
			{
				return this.GetTable<Cat_Perfiles>();
			}
		}
		
		public System.Data.Linq.Table<Cat_Status_Vehiculo> Cat_Status_Vehiculo
		{
			get
			{
				return this.GetTable<Cat_Status_Vehiculo>();
			}
		}
		
		public System.Data.Linq.Table<Cat_Tipo_Vehiculo> Cat_Tipo_Vehiculo
		{
			get
			{
				return this.GetTable<Cat_Tipo_Vehiculo>();
			}
		}
		
		public System.Data.Linq.Table<Cat_Unidad_Gps> Cat_Unidad_Gps
		{
			get
			{
				return this.GetTable<Cat_Unidad_Gps>();
			}
		}
		
		public System.Data.Linq.Table<Ctrl_Gps_Posicion> Ctrl_Gps_Posicion
		{
			get
			{
				return this.GetTable<Ctrl_Gps_Posicion>();
			}
		}
		
		public System.Data.Linq.Table<Ctrl_Usuarios> Ctrl_Usuarios
		{
			get
			{
				return this.GetTable<Ctrl_Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Ctrl_Vehiculos> Ctrl_Vehiculos
		{
			get
			{
				return this.GetTable<Ctrl_Vehiculos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_Reportes")]
		public ISingleResult<Sp_ReportesResult> Sp_Reportes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cve_Gps", DbType="VarChar(16)")] string cve_Gps, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fec_Desde", DbType="VarChar(15)")] string fec_Desde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fec_Hasta", DbType="VarChar(15)")] string fec_Hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hora_Desde", DbType="VarChar(15)")] string hora_Desde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hora_Hasta", DbType="VarChar(15)")] string hora_Hasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cve_Gps, fec_Desde, fec_Hasta, hora_Desde, hora_Hasta);
			return ((ISingleResult<Sp_ReportesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GPS")]
		public ISingleResult<SP_GPSResult> SP_GPS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_GPSResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cat_Perfiles")]
	public partial class Cat_Perfiles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cve_Perfil;
		
		private string _Txt_Perfil;
		
		private System.DateTime _Fec_Actualiza;
		
		private int _Id_Usuario;
		
		private EntitySet<Ctrl_Usuarios> _Ctrl_Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_PerfilChanging(int value);
    partial void OnCve_PerfilChanged();
    partial void OnTxt_PerfilChanging(string value);
    partial void OnTxt_PerfilChanged();
    partial void OnFec_ActualizaChanging(System.DateTime value);
    partial void OnFec_ActualizaChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public Cat_Perfiles()
		{
			this._Ctrl_Usuarios = new EntitySet<Ctrl_Usuarios>(new Action<Ctrl_Usuarios>(this.attach_Ctrl_Usuarios), new Action<Ctrl_Usuarios>(this.detach_Ctrl_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Perfil", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cve_Perfil
		{
			get
			{
				return this._Cve_Perfil;
			}
			set
			{
				if ((this._Cve_Perfil != value))
				{
					this.OnCve_PerfilChanging(value);
					this.SendPropertyChanging();
					this._Cve_Perfil = value;
					this.SendPropertyChanged("Cve_Perfil");
					this.OnCve_PerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Perfil", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Perfil
		{
			get
			{
				return this._Txt_Perfil;
			}
			set
			{
				if ((this._Txt_Perfil != value))
				{
					this.OnTxt_PerfilChanging(value);
					this.SendPropertyChanging();
					this._Txt_Perfil = value;
					this.SendPropertyChanged("Txt_Perfil");
					this.OnTxt_PerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Actualiza", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Actualiza
		{
			get
			{
				return this._Fec_Actualiza;
			}
			set
			{
				if ((this._Fec_Actualiza != value))
				{
					this.OnFec_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fec_Actualiza = value;
					this.SendPropertyChanged("Fec_Actualiza");
					this.OnFec_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Perfiles_Ctrl_Usuarios", Storage="_Ctrl_Usuarios", ThisKey="Cve_Perfil", OtherKey="Cve_Perfil")]
		public EntitySet<Ctrl_Usuarios> Ctrl_Usuarios
		{
			get
			{
				return this._Ctrl_Usuarios;
			}
			set
			{
				this._Ctrl_Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ctrl_Usuarios(Ctrl_Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Perfiles = this;
		}
		
		private void detach_Ctrl_Usuarios(Ctrl_Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Perfiles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cat_Status_Vehiculo")]
	public partial class Cat_Status_Vehiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cve_Tipo_Vehiculo;
		
		private int _Cve_Status_Vehiculo;
		
		private string _Txt_Status_Vehiculo;
		
		private System.DateTime _Fec_Actualiza;
		
		private int _Id_Usuario;
		
		private EntitySet<Ctrl_Vehiculos> _Ctrl_Vehiculos;
		
		private EntityRef<Cat_Tipo_Vehiculo> _Cat_Tipo_Vehiculo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_Tipo_VehiculoChanging(int value);
    partial void OnCve_Tipo_VehiculoChanged();
    partial void OnCve_Status_VehiculoChanging(int value);
    partial void OnCve_Status_VehiculoChanged();
    partial void OnTxt_Status_VehiculoChanging(string value);
    partial void OnTxt_Status_VehiculoChanged();
    partial void OnFec_ActualizaChanging(System.DateTime value);
    partial void OnFec_ActualizaChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public Cat_Status_Vehiculo()
		{
			this._Ctrl_Vehiculos = new EntitySet<Ctrl_Vehiculos>(new Action<Ctrl_Vehiculos>(this.attach_Ctrl_Vehiculos), new Action<Ctrl_Vehiculos>(this.detach_Ctrl_Vehiculos));
			this._Cat_Tipo_Vehiculo = default(EntityRef<Cat_Tipo_Vehiculo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Tipo_Vehiculo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Cve_Tipo_Vehiculo
		{
			get
			{
				return this._Cve_Tipo_Vehiculo;
			}
			set
			{
				if ((this._Cve_Tipo_Vehiculo != value))
				{
					if (this._Cat_Tipo_Vehiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCve_Tipo_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Cve_Tipo_Vehiculo = value;
					this.SendPropertyChanged("Cve_Tipo_Vehiculo");
					this.OnCve_Tipo_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Status_Vehiculo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Cve_Status_Vehiculo
		{
			get
			{
				return this._Cve_Status_Vehiculo;
			}
			set
			{
				if ((this._Cve_Status_Vehiculo != value))
				{
					this.OnCve_Status_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Cve_Status_Vehiculo = value;
					this.SendPropertyChanged("Cve_Status_Vehiculo");
					this.OnCve_Status_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Status_Vehiculo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Status_Vehiculo
		{
			get
			{
				return this._Txt_Status_Vehiculo;
			}
			set
			{
				if ((this._Txt_Status_Vehiculo != value))
				{
					this.OnTxt_Status_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Txt_Status_Vehiculo = value;
					this.SendPropertyChanged("Txt_Status_Vehiculo");
					this.OnTxt_Status_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Actualiza", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Actualiza
		{
			get
			{
				return this._Fec_Actualiza;
			}
			set
			{
				if ((this._Fec_Actualiza != value))
				{
					this.OnFec_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fec_Actualiza = value;
					this.SendPropertyChanged("Fec_Actualiza");
					this.OnFec_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Status_Vehiculo_Ctrl_Vehiculos", Storage="_Ctrl_Vehiculos", ThisKey="Cve_Status_Vehiculo,Cve_Tipo_Vehiculo", OtherKey="Cve_Status_Vehiculo,Cve_Tipo_Vehiculo")]
		public EntitySet<Ctrl_Vehiculos> Ctrl_Vehiculos
		{
			get
			{
				return this._Ctrl_Vehiculos;
			}
			set
			{
				this._Ctrl_Vehiculos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Tipo_Vehiculo_Cat_Status_Vehiculo", Storage="_Cat_Tipo_Vehiculo", ThisKey="Cve_Tipo_Vehiculo", OtherKey="Cve_Tipo_Vehiculo", IsForeignKey=true)]
		public Cat_Tipo_Vehiculo Cat_Tipo_Vehiculo
		{
			get
			{
				return this._Cat_Tipo_Vehiculo.Entity;
			}
			set
			{
				Cat_Tipo_Vehiculo previousValue = this._Cat_Tipo_Vehiculo.Entity;
				if (((previousValue != value) 
							|| (this._Cat_Tipo_Vehiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cat_Tipo_Vehiculo.Entity = null;
						previousValue.Cat_Status_Vehiculo.Remove(this);
					}
					this._Cat_Tipo_Vehiculo.Entity = value;
					if ((value != null))
					{
						value.Cat_Status_Vehiculo.Add(this);
						this._Cve_Tipo_Vehiculo = value.Cve_Tipo_Vehiculo;
					}
					else
					{
						this._Cve_Tipo_Vehiculo = default(int);
					}
					this.SendPropertyChanged("Cat_Tipo_Vehiculo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ctrl_Vehiculos(Ctrl_Vehiculos entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Status_Vehiculo = this;
		}
		
		private void detach_Ctrl_Vehiculos(Ctrl_Vehiculos entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Status_Vehiculo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cat_Tipo_Vehiculo")]
	public partial class Cat_Tipo_Vehiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cve_Tipo_Vehiculo;
		
		private string _Txt_Tipo_Vehiculo;
		
		private System.DateTime _Fec_Actualiza;
		
		private int _Id_Usuario;
		
		private EntitySet<Cat_Status_Vehiculo> _Cat_Status_Vehiculo;
		
		private EntitySet<Ctrl_Vehiculos> _Ctrl_Vehiculos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_Tipo_VehiculoChanging(int value);
    partial void OnCve_Tipo_VehiculoChanged();
    partial void OnTxt_Tipo_VehiculoChanging(string value);
    partial void OnTxt_Tipo_VehiculoChanged();
    partial void OnFec_ActualizaChanging(System.DateTime value);
    partial void OnFec_ActualizaChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public Cat_Tipo_Vehiculo()
		{
			this._Cat_Status_Vehiculo = new EntitySet<Cat_Status_Vehiculo>(new Action<Cat_Status_Vehiculo>(this.attach_Cat_Status_Vehiculo), new Action<Cat_Status_Vehiculo>(this.detach_Cat_Status_Vehiculo));
			this._Ctrl_Vehiculos = new EntitySet<Ctrl_Vehiculos>(new Action<Ctrl_Vehiculos>(this.attach_Ctrl_Vehiculos), new Action<Ctrl_Vehiculos>(this.detach_Ctrl_Vehiculos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Tipo_Vehiculo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cve_Tipo_Vehiculo
		{
			get
			{
				return this._Cve_Tipo_Vehiculo;
			}
			set
			{
				if ((this._Cve_Tipo_Vehiculo != value))
				{
					this.OnCve_Tipo_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Cve_Tipo_Vehiculo = value;
					this.SendPropertyChanged("Cve_Tipo_Vehiculo");
					this.OnCve_Tipo_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Tipo_Vehiculo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Tipo_Vehiculo
		{
			get
			{
				return this._Txt_Tipo_Vehiculo;
			}
			set
			{
				if ((this._Txt_Tipo_Vehiculo != value))
				{
					this.OnTxt_Tipo_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Txt_Tipo_Vehiculo = value;
					this.SendPropertyChanged("Txt_Tipo_Vehiculo");
					this.OnTxt_Tipo_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Actualiza", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Actualiza
		{
			get
			{
				return this._Fec_Actualiza;
			}
			set
			{
				if ((this._Fec_Actualiza != value))
				{
					this.OnFec_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fec_Actualiza = value;
					this.SendPropertyChanged("Fec_Actualiza");
					this.OnFec_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Tipo_Vehiculo_Cat_Status_Vehiculo", Storage="_Cat_Status_Vehiculo", ThisKey="Cve_Tipo_Vehiculo", OtherKey="Cve_Tipo_Vehiculo")]
		public EntitySet<Cat_Status_Vehiculo> Cat_Status_Vehiculo
		{
			get
			{
				return this._Cat_Status_Vehiculo;
			}
			set
			{
				this._Cat_Status_Vehiculo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Tipo_Vehiculo_Ctrl_Vehiculos", Storage="_Ctrl_Vehiculos", ThisKey="Cve_Tipo_Vehiculo", OtherKey="Cve_Tipo_Vehiculo")]
		public EntitySet<Ctrl_Vehiculos> Ctrl_Vehiculos
		{
			get
			{
				return this._Ctrl_Vehiculos;
			}
			set
			{
				this._Ctrl_Vehiculos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cat_Status_Vehiculo(Cat_Status_Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Tipo_Vehiculo = this;
		}
		
		private void detach_Cat_Status_Vehiculo(Cat_Status_Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Tipo_Vehiculo = null;
		}
		
		private void attach_Ctrl_Vehiculos(Ctrl_Vehiculos entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Tipo_Vehiculo = this;
		}
		
		private void detach_Ctrl_Vehiculos(Ctrl_Vehiculos entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Tipo_Vehiculo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cat_Unidad_Gps")]
	public partial class Cat_Unidad_Gps : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cve_GPS;
		
		private string _Num_Tel_Cel;
		
		private string _Num_Serie;
		
		private System.DateTime _Fec_Actualiza;
		
		private int _Id_Usuario;
		
		private EntitySet<Ctrl_Gps_Posicion> _Ctrl_Gps_Posicion;
		
		private EntitySet<Ctrl_Vehiculos> _Ctrl_Vehiculos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_GPSChanging(string value);
    partial void OnCve_GPSChanged();
    partial void OnNum_Tel_CelChanging(string value);
    partial void OnNum_Tel_CelChanged();
    partial void OnNum_SerieChanging(string value);
    partial void OnNum_SerieChanged();
    partial void OnFec_ActualizaChanging(System.DateTime value);
    partial void OnFec_ActualizaChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public Cat_Unidad_Gps()
		{
			this._Ctrl_Gps_Posicion = new EntitySet<Ctrl_Gps_Posicion>(new Action<Ctrl_Gps_Posicion>(this.attach_Ctrl_Gps_Posicion), new Action<Ctrl_Gps_Posicion>(this.detach_Ctrl_Gps_Posicion));
			this._Ctrl_Vehiculos = new EntitySet<Ctrl_Vehiculos>(new Action<Ctrl_Vehiculos>(this.attach_Ctrl_Vehiculos), new Action<Ctrl_Vehiculos>(this.detach_Ctrl_Vehiculos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_GPS", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cve_GPS
		{
			get
			{
				return this._Cve_GPS;
			}
			set
			{
				if ((this._Cve_GPS != value))
				{
					this.OnCve_GPSChanging(value);
					this.SendPropertyChanging();
					this._Cve_GPS = value;
					this.SendPropertyChanged("Cve_GPS");
					this.OnCve_GPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Tel_Cel", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Num_Tel_Cel
		{
			get
			{
				return this._Num_Tel_Cel;
			}
			set
			{
				if ((this._Num_Tel_Cel != value))
				{
					this.OnNum_Tel_CelChanging(value);
					this.SendPropertyChanging();
					this._Num_Tel_Cel = value;
					this.SendPropertyChanged("Num_Tel_Cel");
					this.OnNum_Tel_CelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Serie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Num_Serie
		{
			get
			{
				return this._Num_Serie;
			}
			set
			{
				if ((this._Num_Serie != value))
				{
					this.OnNum_SerieChanging(value);
					this.SendPropertyChanging();
					this._Num_Serie = value;
					this.SendPropertyChanged("Num_Serie");
					this.OnNum_SerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Actualiza", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Actualiza
		{
			get
			{
				return this._Fec_Actualiza;
			}
			set
			{
				if ((this._Fec_Actualiza != value))
				{
					this.OnFec_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fec_Actualiza = value;
					this.SendPropertyChanged("Fec_Actualiza");
					this.OnFec_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Unidad_Gps_Ctrl_Gps_Posicion", Storage="_Ctrl_Gps_Posicion", ThisKey="Cve_GPS", OtherKey="Cve_Gps")]
		public EntitySet<Ctrl_Gps_Posicion> Ctrl_Gps_Posicion
		{
			get
			{
				return this._Ctrl_Gps_Posicion;
			}
			set
			{
				this._Ctrl_Gps_Posicion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Unidad_Gps_Ctrl_Vehiculos", Storage="_Ctrl_Vehiculos", ThisKey="Cve_GPS", OtherKey="Cve_Gps")]
		public EntitySet<Ctrl_Vehiculos> Ctrl_Vehiculos
		{
			get
			{
				return this._Ctrl_Vehiculos;
			}
			set
			{
				this._Ctrl_Vehiculos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ctrl_Gps_Posicion(Ctrl_Gps_Posicion entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Unidad_Gps = this;
		}
		
		private void detach_Ctrl_Gps_Posicion(Ctrl_Gps_Posicion entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Unidad_Gps = null;
		}
		
		private void attach_Ctrl_Vehiculos(Ctrl_Vehiculos entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Unidad_Gps = this;
		}
		
		private void detach_Ctrl_Vehiculos(Ctrl_Vehiculos entity)
		{
			this.SendPropertyChanging();
			entity.Cat_Unidad_Gps = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ctrl_Gps_Posicion")]
	public partial class Ctrl_Gps_Posicion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cve_Ctrl_Gps;
		
		private string _Cve_Gps;
		
		private string _Txt_Msj_Posicion;
		
		private System.DateTime _Fec_Envio_Posicion;
		
		private string _Num_Tel_Cel;
		
		private string _Señal_Gps;
		
		private string _Fix_Time_Gps;
		
		private string _Datos_Validos_Gps;
		
		private string _Latitud_Gps;
		
		private string _Indicador_Latitud_Gps;
		
		private string _Longitud_Gps;
		
		private string _Indicador_Longitud_Gps;
		
		private string _Velocidad_Gps;
		
		private string _IP_Gps;
		
		private int _Puerto_Gps;
		
		private EntityRef<Cat_Unidad_Gps> _Cat_Unidad_Gps;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_Ctrl_GpsChanging(int value);
    partial void OnCve_Ctrl_GpsChanged();
    partial void OnCve_GpsChanging(string value);
    partial void OnCve_GpsChanged();
    partial void OnTxt_Msj_PosicionChanging(string value);
    partial void OnTxt_Msj_PosicionChanged();
    partial void OnFec_Envio_PosicionChanging(System.DateTime value);
    partial void OnFec_Envio_PosicionChanged();
    partial void OnNum_Tel_CelChanging(string value);
    partial void OnNum_Tel_CelChanged();
    partial void OnSeñal_GpsChanging(string value);
    partial void OnSeñal_GpsChanged();
    partial void OnFix_Time_GpsChanging(string value);
    partial void OnFix_Time_GpsChanged();
    partial void OnDatos_Validos_GpsChanging(string value);
    partial void OnDatos_Validos_GpsChanged();
    partial void OnLatitud_GpsChanging(string value);
    partial void OnLatitud_GpsChanged();
    partial void OnIndicador_Latitud_GpsChanging(string value);
    partial void OnIndicador_Latitud_GpsChanged();
    partial void OnLongitud_GpsChanging(string value);
    partial void OnLongitud_GpsChanged();
    partial void OnIndicador_Longitud_GpsChanging(string value);
    partial void OnIndicador_Longitud_GpsChanged();
    partial void OnVelocidad_GpsChanging(string value);
    partial void OnVelocidad_GpsChanged();
    partial void OnIP_GpsChanging(string value);
    partial void OnIP_GpsChanged();
    partial void OnPuerto_GpsChanging(int value);
    partial void OnPuerto_GpsChanged();
    #endregion
		
		public Ctrl_Gps_Posicion()
		{
			this._Cat_Unidad_Gps = default(EntityRef<Cat_Unidad_Gps>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Ctrl_Gps", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cve_Ctrl_Gps
		{
			get
			{
				return this._Cve_Ctrl_Gps;
			}
			set
			{
				if ((this._Cve_Ctrl_Gps != value))
				{
					this.OnCve_Ctrl_GpsChanging(value);
					this.SendPropertyChanging();
					this._Cve_Ctrl_Gps = value;
					this.SendPropertyChanged("Cve_Ctrl_Gps");
					this.OnCve_Ctrl_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Gps", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cve_Gps
		{
			get
			{
				return this._Cve_Gps;
			}
			set
			{
				if ((this._Cve_Gps != value))
				{
					if (this._Cat_Unidad_Gps.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCve_GpsChanging(value);
					this.SendPropertyChanging();
					this._Cve_Gps = value;
					this.SendPropertyChanged("Cve_Gps");
					this.OnCve_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Msj_Posicion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Msj_Posicion
		{
			get
			{
				return this._Txt_Msj_Posicion;
			}
			set
			{
				if ((this._Txt_Msj_Posicion != value))
				{
					this.OnTxt_Msj_PosicionChanging(value);
					this.SendPropertyChanging();
					this._Txt_Msj_Posicion = value;
					this.SendPropertyChanged("Txt_Msj_Posicion");
					this.OnTxt_Msj_PosicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Envio_Posicion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Envio_Posicion
		{
			get
			{
				return this._Fec_Envio_Posicion;
			}
			set
			{
				if ((this._Fec_Envio_Posicion != value))
				{
					this.OnFec_Envio_PosicionChanging(value);
					this.SendPropertyChanging();
					this._Fec_Envio_Posicion = value;
					this.SendPropertyChanged("Fec_Envio_Posicion");
					this.OnFec_Envio_PosicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Tel_Cel", DbType="VarChar(10)")]
		public string Num_Tel_Cel
		{
			get
			{
				return this._Num_Tel_Cel;
			}
			set
			{
				if ((this._Num_Tel_Cel != value))
				{
					this.OnNum_Tel_CelChanging(value);
					this.SendPropertyChanging();
					this._Num_Tel_Cel = value;
					this.SendPropertyChanged("Num_Tel_Cel");
					this.OnNum_Tel_CelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Señal_Gps", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Señal_Gps
		{
			get
			{
				return this._Señal_Gps;
			}
			set
			{
				if ((this._Señal_Gps != value))
				{
					this.OnSeñal_GpsChanging(value);
					this.SendPropertyChanging();
					this._Señal_Gps = value;
					this.SendPropertyChanged("Señal_Gps");
					this.OnSeñal_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fix_Time_Gps", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Fix_Time_Gps
		{
			get
			{
				return this._Fix_Time_Gps;
			}
			set
			{
				if ((this._Fix_Time_Gps != value))
				{
					this.OnFix_Time_GpsChanging(value);
					this.SendPropertyChanging();
					this._Fix_Time_Gps = value;
					this.SendPropertyChanged("Fix_Time_Gps");
					this.OnFix_Time_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datos_Validos_Gps", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Datos_Validos_Gps
		{
			get
			{
				return this._Datos_Validos_Gps;
			}
			set
			{
				if ((this._Datos_Validos_Gps != value))
				{
					this.OnDatos_Validos_GpsChanging(value);
					this.SendPropertyChanging();
					this._Datos_Validos_Gps = value;
					this.SendPropertyChanged("Datos_Validos_Gps");
					this.OnDatos_Validos_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud_Gps", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Latitud_Gps
		{
			get
			{
				return this._Latitud_Gps;
			}
			set
			{
				if ((this._Latitud_Gps != value))
				{
					this.OnLatitud_GpsChanging(value);
					this.SendPropertyChanging();
					this._Latitud_Gps = value;
					this.SendPropertyChanged("Latitud_Gps");
					this.OnLatitud_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indicador_Latitud_Gps", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Indicador_Latitud_Gps
		{
			get
			{
				return this._Indicador_Latitud_Gps;
			}
			set
			{
				if ((this._Indicador_Latitud_Gps != value))
				{
					this.OnIndicador_Latitud_GpsChanging(value);
					this.SendPropertyChanging();
					this._Indicador_Latitud_Gps = value;
					this.SendPropertyChanged("Indicador_Latitud_Gps");
					this.OnIndicador_Latitud_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud_Gps", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Longitud_Gps
		{
			get
			{
				return this._Longitud_Gps;
			}
			set
			{
				if ((this._Longitud_Gps != value))
				{
					this.OnLongitud_GpsChanging(value);
					this.SendPropertyChanging();
					this._Longitud_Gps = value;
					this.SendPropertyChanged("Longitud_Gps");
					this.OnLongitud_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indicador_Longitud_Gps", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Indicador_Longitud_Gps
		{
			get
			{
				return this._Indicador_Longitud_Gps;
			}
			set
			{
				if ((this._Indicador_Longitud_Gps != value))
				{
					this.OnIndicador_Longitud_GpsChanging(value);
					this.SendPropertyChanging();
					this._Indicador_Longitud_Gps = value;
					this.SendPropertyChanged("Indicador_Longitud_Gps");
					this.OnIndicador_Longitud_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Velocidad_Gps", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Velocidad_Gps
		{
			get
			{
				return this._Velocidad_Gps;
			}
			set
			{
				if ((this._Velocidad_Gps != value))
				{
					this.OnVelocidad_GpsChanging(value);
					this.SendPropertyChanging();
					this._Velocidad_Gps = value;
					this.SendPropertyChanged("Velocidad_Gps");
					this.OnVelocidad_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_Gps", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IP_Gps
		{
			get
			{
				return this._IP_Gps;
			}
			set
			{
				if ((this._IP_Gps != value))
				{
					this.OnIP_GpsChanging(value);
					this.SendPropertyChanging();
					this._IP_Gps = value;
					this.SendPropertyChanged("IP_Gps");
					this.OnIP_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puerto_Gps", DbType="Int NOT NULL")]
		public int Puerto_Gps
		{
			get
			{
				return this._Puerto_Gps;
			}
			set
			{
				if ((this._Puerto_Gps != value))
				{
					this.OnPuerto_GpsChanging(value);
					this.SendPropertyChanging();
					this._Puerto_Gps = value;
					this.SendPropertyChanged("Puerto_Gps");
					this.OnPuerto_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Unidad_Gps_Ctrl_Gps_Posicion", Storage="_Cat_Unidad_Gps", ThisKey="Cve_Gps", OtherKey="Cve_GPS", IsForeignKey=true)]
		public Cat_Unidad_Gps Cat_Unidad_Gps
		{
			get
			{
				return this._Cat_Unidad_Gps.Entity;
			}
			set
			{
				Cat_Unidad_Gps previousValue = this._Cat_Unidad_Gps.Entity;
				if (((previousValue != value) 
							|| (this._Cat_Unidad_Gps.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cat_Unidad_Gps.Entity = null;
						previousValue.Ctrl_Gps_Posicion.Remove(this);
					}
					this._Cat_Unidad_Gps.Entity = value;
					if ((value != null))
					{
						value.Ctrl_Gps_Posicion.Add(this);
						this._Cve_Gps = value.Cve_GPS;
					}
					else
					{
						this._Cve_Gps = default(string);
					}
					this.SendPropertyChanged("Cat_Unidad_Gps");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ctrl_Usuarios")]
	public partial class Ctrl_Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cve_Usuario;
		
		private string _Txt_Nombre;
		
		private string _Txt_Paterno;
		
		private string _Txt_Materno;
		
		private string _Txt_Puesto;
		
		private string _Num_Tel_Cel;
		
		private string _Txt_Email;
		
		private int _Cve_Perfil;
		
		private System.DateTime _Fec_Actualiza;
		
		private int _Id_Usuario;
		
		private EntityRef<Cat_Perfiles> _Cat_Perfiles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_UsuarioChanging(int value);
    partial void OnCve_UsuarioChanged();
    partial void OnTxt_NombreChanging(string value);
    partial void OnTxt_NombreChanged();
    partial void OnTxt_PaternoChanging(string value);
    partial void OnTxt_PaternoChanged();
    partial void OnTxt_MaternoChanging(string value);
    partial void OnTxt_MaternoChanged();
    partial void OnTxt_PuestoChanging(string value);
    partial void OnTxt_PuestoChanged();
    partial void OnNum_Tel_CelChanging(string value);
    partial void OnNum_Tel_CelChanged();
    partial void OnTxt_EmailChanging(string value);
    partial void OnTxt_EmailChanged();
    partial void OnCve_PerfilChanging(int value);
    partial void OnCve_PerfilChanged();
    partial void OnFec_ActualizaChanging(System.DateTime value);
    partial void OnFec_ActualizaChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public Ctrl_Usuarios()
		{
			this._Cat_Perfiles = default(EntityRef<Cat_Perfiles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Cve_Usuario
		{
			get
			{
				return this._Cve_Usuario;
			}
			set
			{
				if ((this._Cve_Usuario != value))
				{
					this.OnCve_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Cve_Usuario = value;
					this.SendPropertyChanged("Cve_Usuario");
					this.OnCve_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Nombre
		{
			get
			{
				return this._Txt_Nombre;
			}
			set
			{
				if ((this._Txt_Nombre != value))
				{
					this.OnTxt_NombreChanging(value);
					this.SendPropertyChanging();
					this._Txt_Nombre = value;
					this.SendPropertyChanged("Txt_Nombre");
					this.OnTxt_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Paterno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Paterno
		{
			get
			{
				return this._Txt_Paterno;
			}
			set
			{
				if ((this._Txt_Paterno != value))
				{
					this.OnTxt_PaternoChanging(value);
					this.SendPropertyChanging();
					this._Txt_Paterno = value;
					this.SendPropertyChanged("Txt_Paterno");
					this.OnTxt_PaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Materno", DbType="VarChar(50)")]
		public string Txt_Materno
		{
			get
			{
				return this._Txt_Materno;
			}
			set
			{
				if ((this._Txt_Materno != value))
				{
					this.OnTxt_MaternoChanging(value);
					this.SendPropertyChanging();
					this._Txt_Materno = value;
					this.SendPropertyChanged("Txt_Materno");
					this.OnTxt_MaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Puesto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Puesto
		{
			get
			{
				return this._Txt_Puesto;
			}
			set
			{
				if ((this._Txt_Puesto != value))
				{
					this.OnTxt_PuestoChanging(value);
					this.SendPropertyChanging();
					this._Txt_Puesto = value;
					this.SendPropertyChanged("Txt_Puesto");
					this.OnTxt_PuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Tel_Cel", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Num_Tel_Cel
		{
			get
			{
				return this._Num_Tel_Cel;
			}
			set
			{
				if ((this._Num_Tel_Cel != value))
				{
					this.OnNum_Tel_CelChanging(value);
					this.SendPropertyChanging();
					this._Num_Tel_Cel = value;
					this.SendPropertyChanged("Num_Tel_Cel");
					this.OnNum_Tel_CelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Email", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Txt_Email
		{
			get
			{
				return this._Txt_Email;
			}
			set
			{
				if ((this._Txt_Email != value))
				{
					this.OnTxt_EmailChanging(value);
					this.SendPropertyChanging();
					this._Txt_Email = value;
					this.SendPropertyChanged("Txt_Email");
					this.OnTxt_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Perfil", DbType="Int NOT NULL")]
		public int Cve_Perfil
		{
			get
			{
				return this._Cve_Perfil;
			}
			set
			{
				if ((this._Cve_Perfil != value))
				{
					if (this._Cat_Perfiles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCve_PerfilChanging(value);
					this.SendPropertyChanging();
					this._Cve_Perfil = value;
					this.SendPropertyChanged("Cve_Perfil");
					this.OnCve_PerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Actualiza", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Actualiza
		{
			get
			{
				return this._Fec_Actualiza;
			}
			set
			{
				if ((this._Fec_Actualiza != value))
				{
					this.OnFec_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fec_Actualiza = value;
					this.SendPropertyChanged("Fec_Actualiza");
					this.OnFec_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Perfiles_Ctrl_Usuarios", Storage="_Cat_Perfiles", ThisKey="Cve_Perfil", OtherKey="Cve_Perfil", IsForeignKey=true)]
		public Cat_Perfiles Cat_Perfiles
		{
			get
			{
				return this._Cat_Perfiles.Entity;
			}
			set
			{
				Cat_Perfiles previousValue = this._Cat_Perfiles.Entity;
				if (((previousValue != value) 
							|| (this._Cat_Perfiles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cat_Perfiles.Entity = null;
						previousValue.Ctrl_Usuarios.Remove(this);
					}
					this._Cat_Perfiles.Entity = value;
					if ((value != null))
					{
						value.Ctrl_Usuarios.Add(this);
						this._Cve_Perfil = value.Cve_Perfil;
					}
					else
					{
						this._Cve_Perfil = default(int);
					}
					this.SendPropertyChanged("Cat_Perfiles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ctrl_Vehiculos")]
	public partial class Ctrl_Vehiculos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cve_Vehiculo;
		
		private string _Cve_Gps;
		
		private int _Cve_Tipo_Vehiculo;
		
		private int _Cve_Status_Vehiculo;
		
		private string _Num_Serie_Niv;
		
		private string _Num_Placa;
		
		private string _Txt_sitio;
		
		private System.Nullable<int> _Num_Economico;
		
		private string _Txt_Marca;
		
		private string _Txt_Sub_Marca;
		
		private int _Num_Cilindros;
		
		private System.DateTime _Fec_Actualiza;
		
		private int _Id_Usuario;
		
		private EntityRef<Cat_Status_Vehiculo> _Cat_Status_Vehiculo;
		
		private EntityRef<Cat_Tipo_Vehiculo> _Cat_Tipo_Vehiculo;
		
		private EntityRef<Cat_Unidad_Gps> _Cat_Unidad_Gps;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCve_VehiculoChanging(int value);
    partial void OnCve_VehiculoChanged();
    partial void OnCve_GpsChanging(string value);
    partial void OnCve_GpsChanged();
    partial void OnCve_Tipo_VehiculoChanging(int value);
    partial void OnCve_Tipo_VehiculoChanged();
    partial void OnCve_Status_VehiculoChanging(int value);
    partial void OnCve_Status_VehiculoChanged();
    partial void OnNum_Serie_NivChanging(string value);
    partial void OnNum_Serie_NivChanged();
    partial void OnNum_PlacaChanging(string value);
    partial void OnNum_PlacaChanged();
    partial void OnTxt_sitioChanging(string value);
    partial void OnTxt_sitioChanged();
    partial void OnNum_EconomicoChanging(System.Nullable<int> value);
    partial void OnNum_EconomicoChanged();
    partial void OnTxt_MarcaChanging(string value);
    partial void OnTxt_MarcaChanged();
    partial void OnTxt_Sub_MarcaChanging(string value);
    partial void OnTxt_Sub_MarcaChanged();
    partial void OnNum_CilindrosChanging(int value);
    partial void OnNum_CilindrosChanged();
    partial void OnFec_ActualizaChanging(System.DateTime value);
    partial void OnFec_ActualizaChanged();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    #endregion
		
		public Ctrl_Vehiculos()
		{
			this._Cat_Status_Vehiculo = default(EntityRef<Cat_Status_Vehiculo>);
			this._Cat_Tipo_Vehiculo = default(EntityRef<Cat_Tipo_Vehiculo>);
			this._Cat_Unidad_Gps = default(EntityRef<Cat_Unidad_Gps>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Vehiculo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cve_Vehiculo
		{
			get
			{
				return this._Cve_Vehiculo;
			}
			set
			{
				if ((this._Cve_Vehiculo != value))
				{
					this.OnCve_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Cve_Vehiculo = value;
					this.SendPropertyChanged("Cve_Vehiculo");
					this.OnCve_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Gps", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cve_Gps
		{
			get
			{
				return this._Cve_Gps;
			}
			set
			{
				if ((this._Cve_Gps != value))
				{
					if (this._Cat_Unidad_Gps.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCve_GpsChanging(value);
					this.SendPropertyChanging();
					this._Cve_Gps = value;
					this.SendPropertyChanged("Cve_Gps");
					this.OnCve_GpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Tipo_Vehiculo", DbType="Int NOT NULL")]
		public int Cve_Tipo_Vehiculo
		{
			get
			{
				return this._Cve_Tipo_Vehiculo;
			}
			set
			{
				if ((this._Cve_Tipo_Vehiculo != value))
				{
					if ((this._Cat_Status_Vehiculo.HasLoadedOrAssignedValue || this._Cat_Tipo_Vehiculo.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCve_Tipo_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Cve_Tipo_Vehiculo = value;
					this.SendPropertyChanged("Cve_Tipo_Vehiculo");
					this.OnCve_Tipo_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Status_Vehiculo", DbType="Int NOT NULL")]
		public int Cve_Status_Vehiculo
		{
			get
			{
				return this._Cve_Status_Vehiculo;
			}
			set
			{
				if ((this._Cve_Status_Vehiculo != value))
				{
					if (this._Cat_Status_Vehiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCve_Status_VehiculoChanging(value);
					this.SendPropertyChanging();
					this._Cve_Status_Vehiculo = value;
					this.SendPropertyChanged("Cve_Status_Vehiculo");
					this.OnCve_Status_VehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Serie_Niv", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string Num_Serie_Niv
		{
			get
			{
				return this._Num_Serie_Niv;
			}
			set
			{
				if ((this._Num_Serie_Niv != value))
				{
					this.OnNum_Serie_NivChanging(value);
					this.SendPropertyChanging();
					this._Num_Serie_Niv = value;
					this.SendPropertyChanged("Num_Serie_Niv");
					this.OnNum_Serie_NivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Placa", DbType="VarChar(10)")]
		public string Num_Placa
		{
			get
			{
				return this._Num_Placa;
			}
			set
			{
				if ((this._Num_Placa != value))
				{
					this.OnNum_PlacaChanging(value);
					this.SendPropertyChanging();
					this._Num_Placa = value;
					this.SendPropertyChanged("Num_Placa");
					this.OnNum_PlacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_sitio", DbType="VarChar(50)")]
		public string Txt_sitio
		{
			get
			{
				return this._Txt_sitio;
			}
			set
			{
				if ((this._Txt_sitio != value))
				{
					this.OnTxt_sitioChanging(value);
					this.SendPropertyChanging();
					this._Txt_sitio = value;
					this.SendPropertyChanged("Txt_sitio");
					this.OnTxt_sitioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Economico", DbType="Int")]
		public System.Nullable<int> Num_Economico
		{
			get
			{
				return this._Num_Economico;
			}
			set
			{
				if ((this._Num_Economico != value))
				{
					this.OnNum_EconomicoChanging(value);
					this.SendPropertyChanging();
					this._Num_Economico = value;
					this.SendPropertyChanged("Num_Economico");
					this.OnNum_EconomicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Marca", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Marca
		{
			get
			{
				return this._Txt_Marca;
			}
			set
			{
				if ((this._Txt_Marca != value))
				{
					this.OnTxt_MarcaChanging(value);
					this.SendPropertyChanging();
					this._Txt_Marca = value;
					this.SendPropertyChanged("Txt_Marca");
					this.OnTxt_MarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Sub_Marca", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Sub_Marca
		{
			get
			{
				return this._Txt_Sub_Marca;
			}
			set
			{
				if ((this._Txt_Sub_Marca != value))
				{
					this.OnTxt_Sub_MarcaChanging(value);
					this.SendPropertyChanging();
					this._Txt_Sub_Marca = value;
					this.SendPropertyChanged("Txt_Sub_Marca");
					this.OnTxt_Sub_MarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Cilindros", DbType="Int NOT NULL")]
		public int Num_Cilindros
		{
			get
			{
				return this._Num_Cilindros;
			}
			set
			{
				if ((this._Num_Cilindros != value))
				{
					this.OnNum_CilindrosChanging(value);
					this.SendPropertyChanging();
					this._Num_Cilindros = value;
					this.SendPropertyChanged("Num_Cilindros");
					this.OnNum_CilindrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Actualiza", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fec_Actualiza
		{
			get
			{
				return this._Fec_Actualiza;
			}
			set
			{
				if ((this._Fec_Actualiza != value))
				{
					this.OnFec_ActualizaChanging(value);
					this.SendPropertyChanging();
					this._Fec_Actualiza = value;
					this.SendPropertyChanged("Fec_Actualiza");
					this.OnFec_ActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL")]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Status_Vehiculo_Ctrl_Vehiculos", Storage="_Cat_Status_Vehiculo", ThisKey="Cve_Status_Vehiculo,Cve_Tipo_Vehiculo", OtherKey="Cve_Status_Vehiculo,Cve_Tipo_Vehiculo", IsForeignKey=true)]
		public Cat_Status_Vehiculo Cat_Status_Vehiculo
		{
			get
			{
				return this._Cat_Status_Vehiculo.Entity;
			}
			set
			{
				Cat_Status_Vehiculo previousValue = this._Cat_Status_Vehiculo.Entity;
				if (((previousValue != value) 
							|| (this._Cat_Status_Vehiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cat_Status_Vehiculo.Entity = null;
						previousValue.Ctrl_Vehiculos.Remove(this);
					}
					this._Cat_Status_Vehiculo.Entity = value;
					if ((value != null))
					{
						value.Ctrl_Vehiculos.Add(this);
						this._Cve_Status_Vehiculo = value.Cve_Status_Vehiculo;
						this._Cve_Tipo_Vehiculo = value.Cve_Tipo_Vehiculo;
					}
					else
					{
						this._Cve_Status_Vehiculo = default(int);
						this._Cve_Tipo_Vehiculo = default(int);
					}
					this.SendPropertyChanged("Cat_Status_Vehiculo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Tipo_Vehiculo_Ctrl_Vehiculos", Storage="_Cat_Tipo_Vehiculo", ThisKey="Cve_Tipo_Vehiculo", OtherKey="Cve_Tipo_Vehiculo", IsForeignKey=true)]
		public Cat_Tipo_Vehiculo Cat_Tipo_Vehiculo
		{
			get
			{
				return this._Cat_Tipo_Vehiculo.Entity;
			}
			set
			{
				Cat_Tipo_Vehiculo previousValue = this._Cat_Tipo_Vehiculo.Entity;
				if (((previousValue != value) 
							|| (this._Cat_Tipo_Vehiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cat_Tipo_Vehiculo.Entity = null;
						previousValue.Ctrl_Vehiculos.Remove(this);
					}
					this._Cat_Tipo_Vehiculo.Entity = value;
					if ((value != null))
					{
						value.Ctrl_Vehiculos.Add(this);
						this._Cve_Tipo_Vehiculo = value.Cve_Tipo_Vehiculo;
					}
					else
					{
						this._Cve_Tipo_Vehiculo = default(int);
					}
					this.SendPropertyChanged("Cat_Tipo_Vehiculo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cat_Unidad_Gps_Ctrl_Vehiculos", Storage="_Cat_Unidad_Gps", ThisKey="Cve_Gps", OtherKey="Cve_GPS", IsForeignKey=true)]
		public Cat_Unidad_Gps Cat_Unidad_Gps
		{
			get
			{
				return this._Cat_Unidad_Gps.Entity;
			}
			set
			{
				Cat_Unidad_Gps previousValue = this._Cat_Unidad_Gps.Entity;
				if (((previousValue != value) 
							|| (this._Cat_Unidad_Gps.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cat_Unidad_Gps.Entity = null;
						previousValue.Ctrl_Vehiculos.Remove(this);
					}
					this._Cat_Unidad_Gps.Entity = value;
					if ((value != null))
					{
						value.Ctrl_Vehiculos.Add(this);
						this._Cve_Gps = value.Cve_GPS;
					}
					else
					{
						this._Cve_Gps = default(string);
					}
					this.SendPropertyChanged("Cat_Unidad_Gps");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Sp_ReportesResult
	{
		
		private int _Cve_Ctrl_Gps;
		
		private string _Cve_Gps;
		
		private string _Num_Placa;
		
		private string _Num_Serie_Niv;
		
		private string _Txt_Tipo_Vehiculo;
		
		private string _Fec_Envio_Posicion;
		
		private string _Hora_Envio_Posicion;
		
		private string _Latitud_Gps;
		
		private string _Longitud_Gps;
		
		private string _Txt_Status_Vehiculo;
		
		public Sp_ReportesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Ctrl_Gps", DbType="Int NOT NULL")]
		public int Cve_Ctrl_Gps
		{
			get
			{
				return this._Cve_Ctrl_Gps;
			}
			set
			{
				if ((this._Cve_Ctrl_Gps != value))
				{
					this._Cve_Ctrl_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Gps", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Cve_Gps
		{
			get
			{
				return this._Cve_Gps;
			}
			set
			{
				if ((this._Cve_Gps != value))
				{
					this._Cve_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Placa", DbType="VarChar(10)")]
		public string Num_Placa
		{
			get
			{
				return this._Num_Placa;
			}
			set
			{
				if ((this._Num_Placa != value))
				{
					this._Num_Placa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Serie_Niv", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string Num_Serie_Niv
		{
			get
			{
				return this._Num_Serie_Niv;
			}
			set
			{
				if ((this._Num_Serie_Niv != value))
				{
					this._Num_Serie_Niv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Tipo_Vehiculo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Tipo_Vehiculo
		{
			get
			{
				return this._Txt_Tipo_Vehiculo;
			}
			set
			{
				if ((this._Txt_Tipo_Vehiculo != value))
				{
					this._Txt_Tipo_Vehiculo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Envio_Posicion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Fec_Envio_Posicion
		{
			get
			{
				return this._Fec_Envio_Posicion;
			}
			set
			{
				if ((this._Fec_Envio_Posicion != value))
				{
					this._Fec_Envio_Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Envio_Posicion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Hora_Envio_Posicion
		{
			get
			{
				return this._Hora_Envio_Posicion;
			}
			set
			{
				if ((this._Hora_Envio_Posicion != value))
				{
					this._Hora_Envio_Posicion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud_Gps", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Latitud_Gps
		{
			get
			{
				return this._Latitud_Gps;
			}
			set
			{
				if ((this._Latitud_Gps != value))
				{
					this._Latitud_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud_Gps", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Longitud_Gps
		{
			get
			{
				return this._Longitud_Gps;
			}
			set
			{
				if ((this._Longitud_Gps != value))
				{
					this._Longitud_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txt_Status_Vehiculo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Txt_Status_Vehiculo
		{
			get
			{
				return this._Txt_Status_Vehiculo;
			}
			set
			{
				if ((this._Txt_Status_Vehiculo != value))
				{
					this._Txt_Status_Vehiculo = value;
				}
			}
		}
	}
	
	public partial class SP_GPSResult
	{
		
		private string _Cve_Gps;
		
		private string _Fec_Envio;
		
		private string _Hora_Envio;
		
		private string _Latitud_Gps;
		
		private string _Longitud_Gps;
		
		private string _Velocidad;
		
		private string _Estado_Vehiculo;
		
		public SP_GPSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cve_Gps", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Cve_Gps
		{
			get
			{
				return this._Cve_Gps;
			}
			set
			{
				if ((this._Cve_Gps != value))
				{
					this._Cve_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fec_Envio", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Fec_Envio
		{
			get
			{
				return this._Fec_Envio;
			}
			set
			{
				if ((this._Fec_Envio != value))
				{
					this._Fec_Envio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Envio", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Hora_Envio
		{
			get
			{
				return this._Hora_Envio;
			}
			set
			{
				if ((this._Hora_Envio != value))
				{
					this._Hora_Envio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud_Gps", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Latitud_Gps
		{
			get
			{
				return this._Latitud_Gps;
			}
			set
			{
				if ((this._Latitud_Gps != value))
				{
					this._Latitud_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud_Gps", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Longitud_Gps
		{
			get
			{
				return this._Longitud_Gps;
			}
			set
			{
				if ((this._Longitud_Gps != value))
				{
					this._Longitud_Gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Velocidad", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Velocidad
		{
			get
			{
				return this._Velocidad;
			}
			set
			{
				if ((this._Velocidad != value))
				{
					this._Velocidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Vehiculo", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Estado_Vehiculo
		{
			get
			{
				return this._Estado_Vehiculo;
			}
			set
			{
				if ((this._Estado_Vehiculo != value))
				{
					this._Estado_Vehiculo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
